#!/bin/bash

# Specify the path to the file to be deleted
file_to_delete="/tmp/my_first_directory/betty"

# Check if the file exists before attempting to delete it
if [ -f "$file_to_delete" ]; then
    rm "$file_to_delete"
    echo "File 'betty' has been deleted."
else
    echo "File 'betty' does not exist in /tmp/my_first_directory/."
fi
