#!/bin/bash

# Specify the path to the directory to be deleted
directory_to_delete="/tmp/my_first_directory"

# Check if the directory exists before attempting to delete it
if [ -d "$directory_to_delete" ]; then
    rm -r "$directory_to_delete"
    echo "Directory 'my_first_directory' has been deleted."
else
    echo "Directory 'my_first_directory' does not exist in /tmp/."
fi
